<?php

namespace DM\ConsumerBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends DocumentRepository
{
	
   /* $qb = $this->createQueryBuilder('AcmeStoreBundle:Product')
    ->field('name')->equals('foo')
    ->limit(10)
    ->sort('price', 'ASC')
    ->getQuery()
    ->execute()*/
}