dm_presentation:
    resource: "@DMPresentationBundle/Controller/"
    type:     annotation
    prefix:   /

dm_analytics:
    resource: "@DMAnalyticsBundle/Controller/"
    type:     annotation
    prefix:   /

dm_consumer:
    resource: "@DMConsumerBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

