# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:
#    parameter_name: value

services:
    message_service:
        class: DM\ConsumerBundle\Service\MessageService
        arguments: ["@doctrine_mongodb"]

    report_service:
        class: DM\AnalyticsBundle\Service\ReportService
        arguments: ["@doctrine_mongodb","@trend_result_factory"]

    trend_result_factory:
        class: DM\AnalyticsBundle\Service\TrendResultFactory
        arguments: ~
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

